### ISSUE TITLE
 Will it be open source?

### ISSUE THREAD

**Issue by dream-lmc** [Syntaxerr101/FHookPlus#1]
Hello, is it easy to open source the source code? I want to add a script that can custom add js hooks

**Comment by Syntaxerr101** [comment]
Hey bro, for now its not open source.
I will try to add in the next version an option to import script + script editor and also an option to import frida binary.

**Comment by klxiaoniu** [comment]
> Hey bro, for now its not open source. I will try to add in the next version an option to import script + script editor and also an option to import frida binary.

Please consider open source, so that we can make contributions to this app, for example translating it into different languages.

btw, 1.0.1 is not working on my phone (maybe caused by multidex, since i merge all dex into one and it works), android 14

**Comment by Syntaxerr101** [comment]
Yes sure bro 
I will keep that in mind
I did re-uploaded the apk can u check and confirm the issue with A14?
Thanks for your feedbacks

**Comment by klxiaoniu** [comment]
> Yes sure bro I will put that in mind I did re-uploaded the apk can u check and confirm the issue with A14? Thanks for your feedbacks

it's working now, thanks!

**Comment by Syntaxerr101** [comment]
Its was a signature issue, resigned the apk
