### ISSUE TITLE
App won't open

### ISSUE THREAD

**Issue by privacyguy123** [Syntaxerr101/FHookPlus#2]
When hooked with SSL killer. Is there some other way around this?

**Comment by Syntaxerr101** [comment]
Give more details about the issue 
is this an issue with fhook or ssl killer?

**Comment by privacyguy123** [comment]
Sorry I noticed I'm on the wrong repo - woops. App auto crashes when hooked with SSL Killer, does this mean it has some sort of hook protection?

**Comment by Syntaxerr101** [comment]
> Sorry I noticed I'm on the wrong repo - woops. App auto crashes when hooked with SSL Killer, does this mean it has some sort of hook protection? 

Possible xposed hook detection, u have to inspect the code
