### ISSUE TITLE
The app is crashing!!

### ISSUE THREAD

**Issue by ENIGMATIC-GUY** [Syntaxerr101/FHookPlus#3]
The app is crashing in android 13 custom rom?.....any fix?

**Comment by Dev4Mod** [comment]
This is happening because the generated apk has multiple small dex, it is possibly using an old version of Gradle, to resolve this you can use "multiDexEnable False" in build.gradle

**Comment by Syntaxerr101** [comment]
Hey thank u for your feedbacks

Am using Aide pro for development on my phone 😅
I did disable multi-dex but still generating apk with multiple dex 
I did re-upload the apk, can u confirm if the issue still persist

**Comment by Syntaxerr101** [comment]
> This is happening because the generated apk has multiple small dex, it is possibly using an old version of Gradle, to resolve this you can use "multiDexEnable False" in build.gradle

Check the re-uploaded apk it's fixed
