### ISSUE TITLE
no default frida binary and  Script ？

### ISSUE THREAD

**Issue by klcb2010** [Syntaxerr101/FHookPlus#5]
It would be very difficult to use without no default frida binary and  Script

**Comment by Syntaxerr101** [comment]
You can find many around GitHub 
Just download then import >> 

frida:
https://github.com/frida/frida/releases
https://github.com/hzzheyang/strongR-frida-android/releases
https://github.com/zer0def/undetected-frida/releases
https://github.com/Ylarod/Florida/releases
...

scripts:
https://github.com/m0bilesecurity/Frida-Mobile-Scripts
https://github.com/rsenet/FriList
https://github.com/seemoo-lab/frida-scripts
https://github.com/0xdea/frida-scripts
https://github.com/physics-sec/frida-scripts
https://codeshare.frida.re/
...
